### ISSUE TITLE
Error: no database "biocarta" for species "hsapiens" when running your enrichr file

### ISSUE THREAD

**Issue by ArcticPeAr** [bpickett/Pathway2Targets#1]
Thanks for creating this package!

I am trying to run it first on your enrichr file as such: 

`Rscript /home/Pathway2Targets/Pathways2Targets2.R /home/Pathway2Targets/Example_enrichr_Input.csv
`
 but I keep getting the error message:
> Error: no database "biocarta" for species "hsapiens"
> Execution halted

Using the graphite-package, no Biocarta is available so I assumed that it was indeed asking for a local Reactome pathway database. 
Downloading the Reactome database did not work using this line  
`prepareSPIA(humanReactome, "Reactome", print.names=TRUE)
`
as humanReactome is reported to not be an object in my R console (not found).

I downloaded it thus using:
`library(graphite)`
`reactome_pathways <- pathways(species = "hsapiens", database = "reactome")`
`prepared_pathways <- prepareSPIA(db = reactome_pathways, pathwaySetName = Pathway2Targets/Reactome
` 

An RDS file is generated in my Pathway2Targets folder.  But running the same Rscript as above did not work. Tried renaming the RDS file as "reactome", but to no avail.

How can I run your package? 

My system is MXLinux 23.11 with R version 4.3.2 -"Eye Holes"

Thanks in advance!

**Comment by bpickett** [comment]
Unfortunately, BioCarta stopped being included in the more up-to-date versions of the graphite package. Since the BioCarta database isn't in the package, the code throws an error. There are a few potential solutions to this issue:
1) you could remove the line(s) in the input file that contain pathway information from BioCarta, so that the script doesn't try to find the database
2) you could install R 3.6.1, with the versions of Bioconductor and graphite that are compatible with that version

If you want to run SPIA on a list of DEGs, you'll need to first save the Reactome database in an object and then use the prepareSPIA command. Something like this should make Reactome work
#first set the working directory to where you'd like to save the file, then
humanReactome <- pathways("hsapiens", "reactome")
prepareSPIA(humanReactome, "reactome")

You'll then need to make sure to use the same working directory anytime you're trying to load the files into SPIA.

**Comment by ArcticPeAr** [comment]
Thanks for your quick reply!
I have gotten further using Pathway2Targets with R 3.6.3 , but now I am getting this error:

```
[1] "Working...Pathway 1 of 18 : Cell Cycle"
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Backtrace:
     ▆
  1. ├─biomaRt::getBM(...)
  2. │ └─BiocFileCache::BiocFileCache(cache, ask = FALSE)
  3. │   └─BiocFileCache:::.sql_create_db(bfc)
  4. │     └─BiocFileCache:::.sql_validate_version(bfc)
  5. │       └─BiocFileCache:::.sql_schema_version(bfc)
  6. │         ├─base::tryCatch(...)
  7. │         │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  8. │         └─tbl(src, "metadata") %>% collect(Inf)
  9. ├─dplyr::collect(., Inf)
 10. └─dbplyr:::collect.tbl_sql(., Inf)
 11.   ├─base::tryCatch(...)
 12.   │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 13.   │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 14.   │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 15.   └─dbplyr::db_collect(x$src$con, sql, n = n, warn_incomplete = warn_incomplete, ...)
 16.     └─rlang (local) `<fn>`()
 17.       └─rlang:::check_dots(env, error, action, call)
 18.         └─rlang:::action_dots(...)
 19.           ├─base (local) try_dots(...)
 20.           └─rlang (local) action(...)
Execution halted
The command '/bin/sh -c Rscript --vanilla "/Pathway2Targets/Pathways2Targets2.R" "/Pathway2Targets/Example_enrichr_Input.csv"' returned a non-zero code: 1

```
This is using the enrichr example file in your repository. 

It looks like there is an Inf being passed to dplyrs collect(), but I cannot figure out why?

Thanks again!

**Comment by bpickett** [comment]
the collect() function has a bug in one of the BioConductor packages that this software uses, and isn't an issue with Pathway2Targets itself. A patch was recently released that fixes the bug. There are a few options to fix it described here: 
[https://stackoverflow.com/questions/77370659/error-failed-to-collect-lazy-table-caused-by-error-in-db-collect-using](https://stackoverflow.com/questions/77370659/error-failed-to-collect-lazy-table-caused-by-error-in-db-collect-using)
